
version: 0.2
env:
  shell: bash
  variables:
    # This var is used to define which version of terraform to use
    # This can be overridden by passing a TF_VERSION var to the build
    TF_VERSION: "1.3.7"
    # This var tells terraform that we're running in a CI/CD pipeline
    TF_IN_AUTOMATION: "true"
    # This var tells terraform to disable prompts for missing variables
    TF_INPUT: "false"
phases:
  install:
    commands:
      # Install terraform in /usr/bin
      - cd /usr/bin
      - curl -s -qL -o terraform.zip "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip -o terraform.zip

  build:
    commands:
      # Verify the values of vars passed in via the project
      - echo "${TF_WORKSPACE}"
      - echo "${TF_ROOT_SOURCE_VAR_NAME}"
      - echo "${TF_ROOT_PATH}"
      - echo "${TF_PLAN_SOURCE_VAR_NAME}"
      - echo "${TF_PLAN_PATH}"

      # Set the root dir for running terraform commands
      - TF_ROOT="${!TF_ROOT_SOURCE_VAR_NAME}"
      - echo "${TF_ROOT}"
      - TF_ROOT_FULL_PATH="${TF_ROOT}/${TF_ROOT_PATH}"
      - echo "${TF_ROOT_FULL_PATH}"
      # Change to that directory
      - cd "${TF_ROOT_FULL_PATH}"

      # Set the path to the plan file
      - TF_PLAN_ROOT="${!TF_PLAN_SOURCE_VAR_NAME}"
      - echo "${TF_PLAN_ROOT}"
      - TF_PLAN_FULL_PATH="${TF_PLAN_ROOT}/${TF_PLAN_PATH}"
      - echo "${TF_PLAN_FULL_PATH}"

      - ls -l "${TF_PLAN_FULL_PATH}"

      # Apply the previously saved plan file
      #- terraform apply -var-file "${TFVARS_FULL_PATH}" -auto-approve
      - echo "terraform apply ${TF_PLAN_FULL_PATH}"

