name: CDK Synth
on: [push]
# Required permissions
permissions: read-all
jobs:
  trunk_check:
    name: Trunk Check Runner
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: yarn-install-services
        working-directory: ./doorway-services
        run: yarn install
      - name: synth-services
        run: cdk synth
        working-directory: ./doorway-services
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
          ENVIRONMENT: dev
      - name: deploy-services
        run: cdk deploy --all --require-approval never
        working-directory: ./doorway-services
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
          ENVIRONMENT: dev
