name: Trunk Check
on: [push]
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      network: ${{ steps.filter.outputs.network }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          network:
            - 'doorway-network/**'
  # JOB to build and test backend code
  network:
    needs: changes
    if: ${{ needs.changes.outputs.network == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trunk Check
        run:
            curl https://get.trunk.io -fsSL | bash
            cd ./doorway-network
            trunk check
