name: Trunk Check
on: [push]
# Required permissions
permissions: read-all
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      network: ${{ steps.filter.outputs.network }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            network:
              - 'doorway-network/**'
  # JOB to build and test backend code
  network:
    needs: changes
    if: ${{ needs.changes.outputs.network == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trunk Install
        run: curl https://get.trunk.io -fsSL | bash
      - name: Trunk Check
        working-directory: ./doorway-network
        run: ls -latr
